"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.searchRecords = exports.searchDownload = exports.searchAbort = exports.searchGet = exports.searchDelete = exports.searchCreate = exports.searchesList = exports.recordVersionsList = exports.recordGet = exports.objectsList = exports.recordsUnlock = exports.recordChildrenList = exports.recordLock = exports.recordLockGet = exports.recordUnlock = exports.recordsLock = exports.deletionRecordsList = exports.deletionGet = exports.deletionsList = exports.backupsHealthGet = exports.BackupsHealthStatus = exports.RecordDeletedSource = exports.SearchFiltersMode = void 0;
/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * GRAX API
 * OpenAPI spec version: 0.0.1
 */
var axios_1 = require("axios");
// eslint-disable-next-line @typescript-eslint/no-redeclare
exports.SearchFiltersMode = {
    and: 'and',
    or: 'or',
};
// eslint-disable-next-line @typescript-eslint/no-redeclare
exports.RecordDeletedSource = {
    grax: 'grax',
    source: 'source',
};
// eslint-disable-next-line @typescript-eslint/no-redeclare
exports.BackupsHealthStatus = {
    ok: 'ok',
    warning: 'warning',
    error: 'error',
    unknown: 'unknown',
};
/**
* Get the health of Auto Backup.
* @summary Get Auto Backup health
*/
var backupsHealthGet = function (params, options) {
    return axios_1.default.get("/api/v1/backups/health", __assign(__assign({}, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.backupsHealthGet = backupsHealthGet;
/**
 * @summary List Delete Forever deletions
 */
var deletionsList = function (orgID, params, options) {
    return axios_1.default.get("/api/v1/salesforce/".concat(orgID, "/deletions"), __assign(__assign({}, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.deletionsList = deletionsList;
/**
 * @summary Get Delete Forever deletion
 */
var deletionGet = function (orgID, id, options) {
    return axios_1.default.get("/api/v1/salesforce/".concat(orgID, "/deletions/").concat(id), options);
};
exports.deletionGet = deletionGet;
/**
 * @summary List Delete Forever deletion records
 */
var deletionRecordsList = function (orgID, id, params, options) {
    return axios_1.default.get("/api/v1/salesforce/".concat(orgID, "/deletions/").concat(id, "/records"), __assign(__assign({}, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.deletionRecordsList = deletionRecordsList;
/**
 * @summary Lock multiple records
 */
var recordsLock = function (orgID, object, recordsLockBody, options) {
    return axios_1.default.post("/api/v1/salesforce/".concat(orgID, "/objects/").concat(object, "/lock"), recordsLockBody, options);
};
exports.recordsLock = recordsLock;
/**
 * @summary Unlock single record
 */
var recordUnlock = function (orgID, object, id, options) {
    return axios_1.default.delete("/api/v1/salesforce/".concat(orgID, "/objects/").concat(object, "/records/").concat(id, "/lock"), options);
};
exports.recordUnlock = recordUnlock;
/**
 * @summary Get record lock
 */
var recordLockGet = function (orgID, object, id, options) {
    return axios_1.default.get("/api/v1/salesforce/".concat(orgID, "/objects/").concat(object, "/records/").concat(id, "/lock"), options);
};
exports.recordLockGet = recordLockGet;
/**
 * @summary Lock single record
 */
var recordLock = function (orgID, object, id, options) {
    return axios_1.default.post("/api/v1/salesforce/".concat(orgID, "/objects/").concat(object, "/records/").concat(id, "/lock"), undefined, options);
};
exports.recordLock = recordLock;
/**
 * @summary List record children
 */
var recordChildrenList = function (orgID, object, id, mod, params, options) {
    return axios_1.default.get("/api/v1/salesforce/".concat(orgID, "/objects/").concat(object, "/records/").concat(id, "/versions/").concat(mod, "/children"), __assign(__assign({}, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.recordChildrenList = recordChildrenList;
/**
 * @summary Unlock multiple records
 */
var recordsUnlock = function (orgID, object, recordsUnlockBody, options) {
    return axios_1.default.post("/api/v1/salesforce/".concat(orgID, "/objects/").concat(object, "/unlock"), recordsUnlockBody, options);
};
exports.recordsUnlock = recordsUnlock;
/**
 * @summary List objects
 */
var objectsList = function (params, options) {
    return axios_1.default.get("/api/v2/objects", __assign(__assign({}, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.objectsList = objectsList;
/**
 * @summary Get record
 */
var recordGet = function (object, id, params, options) {
    return axios_1.default.get("/api/v2/objects/".concat(object, "/records/").concat(id), __assign(__assign({}, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.recordGet = recordGet;
/**
 * @summary List record versions
 */
var recordVersionsList = function (object, id, params, options) {
    return axios_1.default.get("/api/v2/objects/".concat(object, "/records/").concat(id, "/versions"), __assign(__assign({}, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.recordVersionsList = recordVersionsList;
/**
 * @summary List searches
 */
var searchesList = function (params, options) {
    return axios_1.default.get("/api/v2/searches", __assign(__assign({}, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.searchesList = searchesList;
/**
 * @summary Create search
 */
var searchCreate = function (searchCreate, options) {
    return axios_1.default.post("/api/v2/searches", searchCreate, options);
};
exports.searchCreate = searchCreate;
/**
 * @summary Delete search
 */
var searchDelete = function (id, options) {
    return axios_1.default.delete("/api/v2/searches/".concat(id), options);
};
exports.searchDelete = searchDelete;
/**
 * @summary Get search
 */
var searchGet = function (id, options) {
    return axios_1.default.get("/api/v2/searches/".concat(id), options);
};
exports.searchGet = searchGet;
/**
 * @summary Abort search
 */
var searchAbort = function (id, options) {
    return axios_1.default.post("/api/v2/searches/".concat(id, "/abort"), undefined, options);
};
exports.searchAbort = searchAbort;
/**
 * @summary Download search results
 */
var searchDownload = function (id, params, options) {
    return axios_1.default.get("/api/v2/searches/".concat(id, "/download"), __assign(__assign({ responseType: 'blob' }, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.searchDownload = searchDownload;
/**
 * @summary Read search result records
 */
var searchRecords = function (id, params, options) {
    return axios_1.default.get("/api/v2/searches/".concat(id, "/records"), __assign(__assign({}, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.searchRecords = searchRecords;
