/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AuditUser model module.
 * @module model/AuditUser
 * @version 0.0.1
 */
export default class AuditUser {
  /**
   * Constructs a new <code>AuditUser</code>.
   * @alias module:model/AuditUser
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuditUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuditUser} obj Optional instance to populate.
   * @return {module:model/AuditUser} The populated <code>AuditUser</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuditUser();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * The email of the user.
 * @member {String} email
 */
AuditUser.prototype.email = undefined;

/**
 * The ID of the user.
 * @member {String} id
 */
AuditUser.prototype.id = undefined;

/**
 * The username of the user.
 * @member {String} name
 */
AuditUser.prototype.name = undefined;

