/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BackupsHealth model module.
 * @module model/BackupsHealth
 * @version 0.0.1
 */
export default class BackupsHealth {
  /**
   * Constructs a new <code>BackupsHealth</code>.
   * @alias module:model/BackupsHealth
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BackupsHealth</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BackupsHealth} obj Optional instance to populate.
   * @return {module:model/BackupsHealth} The populated <code>BackupsHealth</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BackupsHealth();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
BackupsHealth.StatusEnum = {
  /**
   * value: "ok"
   * @const
   */
  ok: "ok",

  /**
   * value: "warning"
   * @const
   */
  warning: "warning",

  /**
   * value: "error"
   * @const
   */
  error: "error",

  /**
   * value: "unknown"
   * @const
   */
  unknown: "unknown"
};
/**
 * @member {module:model/BackupsHealth.StatusEnum} status
 */
BackupsHealth.prototype.status = undefined;

