/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ChildRecord model module.
 * @module model/ChildRecord
 * @version 0.0.1
 */
export default class ChildRecord {
  /**
   * Constructs a new <code>ChildRecord</code>.
   * @alias module:model/ChildRecord
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChildRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChildRecord} obj Optional instance to populate.
   * @return {module:model/ChildRecord} The populated <code>ChildRecord</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChildRecord();
      if (data.hasOwnProperty('deleteSource'))
        obj.deleteSource = ApiClient.convertToType(data['deleteSource'], 'String');
      if (data.hasOwnProperty('deletedAt'))
        obj.deletedAt = ApiClient.convertToType(data['deletedAt'], 'Date');
      if (data.hasOwnProperty('fields'))
        obj.fields = ApiClient.convertToType(data['fields'], {'String': 'String'});
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('modifiedAt'))
        obj.modifiedAt = ApiClient.convertToType(data['modifiedAt'], 'Date');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('salesforceURL'))
        obj.salesforceURL = ApiClient.convertToType(data['salesforceURL'], 'String');
    }
    return obj;
  }
}

/**
 * The delete source of the record, if it has been deleted. Can be 'grax' or 'salesforce'.
 * @member {String} deleteSource
 */
ChildRecord.prototype.deleteSource = undefined;

/**
 * The time the record was deleted, if it has been deleted.
 * @member {Date} deletedAt
 */
ChildRecord.prototype.deletedAt = undefined;

/**
 * The fields of the record, if requested.
 * @member {Object.<String, String>} fields
 */
ChildRecord.prototype.fields = undefined;

/**
 * The ID of the record.
 * @member {String} id
 */
ChildRecord.prototype.id = undefined;

/**
 * The time the record was last modified.
 * @member {Date} modifiedAt
 */
ChildRecord.prototype.modifiedAt = undefined;

/**
 * The name of the record, if requested.
 * @member {String} name
 */
ChildRecord.prototype.name = undefined;

/**
 * The object of the record.
 * @member {String} _object
 */
ChildRecord.prototype._object = undefined;

/**
 * The Salesforce URL of the record.
 * @member {String} salesforceURL
 */
ChildRecord.prototype.salesforceURL = undefined;

