/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DeletionCaller from './DeletionCaller';

/**
 * The Deletion model module.
 * @module model/Deletion
 * @version 0.0.1
 */
export default class Deletion {
  /**
   * Constructs a new <code>Deletion</code>.
   * @alias module:model/Deletion
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Deletion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Deletion} obj Optional instance to populate.
   * @return {module:model/Deletion} The populated <code>Deletion</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Deletion();
      if (data.hasOwnProperty('caller'))
        obj.caller = DeletionCaller.constructFromObject(data['caller']);
      if (data.hasOwnProperty('cascade'))
        obj.cascade = ApiClient.convertToType(data['cascade'], 'Boolean');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('forceCascadeObjects'))
        obj.forceCascadeObjects = ApiClient.convertToType(data['forceCascadeObjects'], ['String']);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('skipDeletedCheck'))
        obj.skipDeletedCheck = ApiClient.convertToType(data['skipDeletedCheck'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/DeletionCaller} caller
 */
Deletion.prototype.caller = undefined;

/**
 * @member {Boolean} cascade
 */
Deletion.prototype.cascade = undefined;

/**
 * @member {Date} createdAt
 */
Deletion.prototype.createdAt = undefined;

/**
 * @member {Array.<String>} forceCascadeObjects
 */
Deletion.prototype.forceCascadeObjects = undefined;

/**
 * @member {String} id
 */
Deletion.prototype.id = undefined;

/**
 * @member {String} _object
 */
Deletion.prototype._object = undefined;

/**
 * @member {Boolean} skipDeletedCheck
 */
Deletion.prototype.skipDeletedCheck = undefined;

