/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DeletionCaller model module.
 * @module model/DeletionCaller
 * @version 0.0.1
 */
export default class DeletionCaller {
  /**
   * Constructs a new <code>DeletionCaller</code>.
   * @alias module:model/DeletionCaller
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeletionCaller</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeletionCaller} obj Optional instance to populate.
   * @return {module:model/DeletionCaller} The populated <code>DeletionCaller</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeletionCaller();
      if (data.hasOwnProperty('headers'))
        obj.headers = ApiClient.convertToType(data['headers'], {'String': ['String']});
      if (data.hasOwnProperty('remoteAddr'))
        obj.remoteAddr = ApiClient.convertToType(data['remoteAddr'], 'String');
      if (data.hasOwnProperty('userID'))
        obj.userID = ApiClient.convertToType(data['userID'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Object.<String, Array.<String>>} headers
 */
DeletionCaller.prototype.headers = undefined;

/**
 * @member {String} remoteAddr
 */
DeletionCaller.prototype.remoteAddr = undefined;

/**
 * @member {String} userID
 */
DeletionCaller.prototype.userID = undefined;

