/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DeletionRecord model module.
 * @module model/DeletionRecord
 * @version 0.0.1
 */
export default class DeletionRecord {
  /**
   * Constructs a new <code>DeletionRecord</code>.
   * @alias module:model/DeletionRecord
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeletionRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeletionRecord} obj Optional instance to populate.
   * @return {module:model/DeletionRecord} The populated <code>DeletionRecord</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeletionRecord();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('modifiedAt'))
        obj.modifiedAt = ApiClient.convertToType(data['modifiedAt'], 'Date');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('purgedAt'))
        obj.purgedAt = ApiClient.convertToType(data['purgedAt'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
DeletionRecord.prototype.id = undefined;

/**
 * @member {Date} modifiedAt
 */
DeletionRecord.prototype.modifiedAt = undefined;

/**
 * @member {String} _object
 */
DeletionRecord.prototype._object = undefined;

/**
 * @member {Date} purgedAt
 */
DeletionRecord.prototype.purgedAt = undefined;

