/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Deletion from './Deletion';

/**
 * The DeletionsPage model module.
 * @module model/DeletionsPage
 * @version 0.0.1
 */
export default class DeletionsPage {
  /**
   * Constructs a new <code>DeletionsPage</code>.
   * @alias module:model/DeletionsPage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeletionsPage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeletionsPage} obj Optional instance to populate.
   * @return {module:model/DeletionsPage} The populated <code>DeletionsPage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeletionsPage();
      if (data.hasOwnProperty('deletions'))
        obj.deletions = ApiClient.convertToType(data['deletions'], [Deletion]);
      if (data.hasOwnProperty('nextPageToken'))
        obj.nextPageToken = ApiClient.convertToType(data['nextPageToken'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Deletion>} deletions
 */
DeletionsPage.prototype.deletions = undefined;

/**
 * Token to retrieve the next page of results, blank if done.
 * @member {String} nextPageToken
 */
DeletionsPage.prototype.nextPageToken = undefined;

