/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ErrorBody model module.
 * @module model/ErrorBody
 * @version 0.0.1
 */
export default class ErrorBody {
  /**
   * Constructs a new <code>ErrorBody</code>.
   * @alias module:model/ErrorBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ErrorBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ErrorBody} obj Optional instance to populate.
   * @return {module:model/ErrorBody} The populated <code>ErrorBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ErrorBody();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ErrorBody.prototype.id = undefined;

/**
 * @member {String} message
 */
ErrorBody.prototype.message = undefined;

