/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ModelObject model module.
 * @module model/ModelObject
 * @version 0.0.1
 */
export default class ModelObject {
  /**
   * Constructs a new <code>ModelObject</code>.
   * @alias module:model/ModelObject
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModelObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelObject} obj Optional instance to populate.
   * @return {module:model/ModelObject} The populated <code>ModelObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModelObject();
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * Object label.
 * @member {String} label
 */
ModelObject.prototype.label = undefined;

/**
 * Object name.
 * @member {String} name
 */
ModelObject.prototype.name = undefined;

