/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ModelObject from './ModelObject';

/**
 * The ObjectsPage model module.
 * @module model/ObjectsPage
 * @version 0.0.1
 */
export default class ObjectsPage {
  /**
   * Constructs a new <code>ObjectsPage</code>.
   * @alias module:model/ObjectsPage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ObjectsPage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ObjectsPage} obj Optional instance to populate.
   * @return {module:model/ObjectsPage} The populated <code>ObjectsPage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ObjectsPage();
      if (data.hasOwnProperty('nextPageToken'))
        obj.nextPageToken = ApiClient.convertToType(data['nextPageToken'], 'String');
      if (data.hasOwnProperty('objects'))
        obj.objects = ApiClient.convertToType(data['objects'], [ModelObject]);
    }
    return obj;
  }
}

/**
 * Token to retrieve the next page of results, blank if done.
 * @member {String} nextPageToken
 */
ObjectsPage.prototype.nextPageToken = undefined;

/**
 * Objects.
 * @member {Array.<module:model/ModelObject>} objects
 */
ObjectsPage.prototype.objects = undefined;

