/**
 * GRAX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelObject from './ModelObject';

/**
 * The ObjectsPage model module.
 * @module model/ObjectsPage
 * @version 0.0.1
 */
class ObjectsPage {
    /**
     * Constructs a new <code>ObjectsPage</code>.
     * @alias module:model/ObjectsPage
     */
    constructor() { 
        
        ObjectsPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ObjectsPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObjectsPage} obj Optional instance to populate.
     * @return {module:model/ObjectsPage} The populated <code>ObjectsPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectsPage();

            if (data.hasOwnProperty('nextPageToken')) {
                obj['nextPageToken'] = ApiClient.convertToType(data['nextPageToken'], 'String');
            }
            if (data.hasOwnProperty('objects')) {
                obj['objects'] = ApiClient.convertToType(data['objects'], [ModelObject]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ObjectsPage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ObjectsPage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['nextPageToken'] && !(typeof data['nextPageToken'] === 'string' || data['nextPageToken'] instanceof String)) {
            throw new Error("Expected the field `nextPageToken` to be a primitive type in the JSON string but got " + data['nextPageToken']);
        }
        if (data['objects']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['objects'])) {
                throw new Error("Expected the field `objects` to be an array in the JSON data but got " + data['objects']);
            }
            // validate the optional field `objects` (array)
            for (const item of data['objects']) {
                ModelObject.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Token to retrieve the next page of results, blank if done.
 * @member {String} nextPageToken
 */
ObjectsPage.prototype['nextPageToken'] = undefined;

/**
 * Objects.
 * @member {Array.<module:model/ModelObject>} objects
 */
ObjectsPage.prototype['objects'] = undefined;






export default ObjectsPage;

