/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RecordLockID model module.
 * @module model/RecordLockID
 * @version 0.0.1
 */
export default class RecordLockID {
  /**
   * Constructs a new <code>RecordLockID</code>.
   * @alias module:model/RecordLockID
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RecordLockID</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecordLockID} obj Optional instance to populate.
   * @return {module:model/RecordLockID} The populated <code>RecordLockID</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RecordLockID();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('note'))
        obj.note = ApiClient.convertToType(data['note'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
RecordLockID.prototype.id = undefined;

/**
 * @member {String} note
 */
RecordLockID.prototype.note = undefined;

