/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AuditUser from './AuditUser';

/**
 * The RecordDeleted model module.
 * @module model/RecordDeleted
 * @version 0.0.1
 */
export default class RecordDeleted {
  /**
   * Constructs a new <code>RecordDeleted</code>.
   * @alias module:model/RecordDeleted
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RecordDeleted</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecordDeleted} obj Optional instance to populate.
   * @return {module:model/RecordDeleted} The populated <code>RecordDeleted</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RecordDeleted();
      if (data.hasOwnProperty('activityID'))
        obj.activityID = ApiClient.convertToType(data['activityID'], 'String');
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], 'String');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Date');
      if (data.hasOwnProperty('user'))
        obj.user = AuditUser.constructFromObject(data['user']);
    }
    return obj;
  }
}

/**
 * ID of the activity that deleted the record.
 * @member {String} activityID
 */
RecordDeleted.prototype.activityID = undefined;

/**
 * Allowed values for the <code>source</code> property.
 * @enum {String}
 * @readonly
 */
RecordDeleted.SourceEnum = {
  /**
   * value: "grax"
   * @const
   */
  grax: "grax",

  /**
   * value: "source"
   * @const
   */
  source: "source"
};
/**
 * Source of the delete.
 * @member {module:model/RecordDeleted.SourceEnum} source
 */
RecordDeleted.prototype.source = undefined;

/**
 * Time the record was deleted.
 * @member {Date} time
 */
RecordDeleted.prototype.time = undefined;

/**
 * @member {module:model/AuditUser} user
 */
RecordDeleted.prototype.user = undefined;

