/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RecordLock model module.
 * @module model/RecordLock
 * @version 0.0.1
 */
export default class RecordLock {
  /**
   * Constructs a new <code>RecordLock</code>.
   * @alias module:model/RecordLock
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RecordLock</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecordLock} obj Optional instance to populate.
   * @return {module:model/RecordLock} The populated <code>RecordLock</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RecordLock();
      if (data.hasOwnProperty('locked'))
        obj.locked = ApiClient.convertToType(data['locked'], 'Date');
      if (data.hasOwnProperty('lockedID'))
        obj.lockedID = ApiClient.convertToType(data['lockedID'], 'String');
      if (data.hasOwnProperty('note'))
        obj.note = ApiClient.convertToType(data['note'], 'String');
      if (data.hasOwnProperty('userID'))
        obj.userID = ApiClient.convertToType(data['userID'], 'String');
    }
    return obj;
  }
}

/**
 * Time the record was locked. If not present, the record is not locked.
 * @member {Date} locked
 */
RecordLock.prototype.locked = undefined;

/**
 * ID of the record causing this record to be locked
 * @member {String} lockedID
 */
RecordLock.prototype.lockedID = undefined;

/**
 * Note about the lock
 * @member {String} note
 */
RecordLock.prototype.note = undefined;

/**
 * ID of the user who locked the record
 * @member {String} userID
 */
RecordLock.prototype.userID = undefined;

