/**
 * GRAX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RecordLockID from './RecordLockID';

/**
 * The RecordsLockRequest model module.
 * @module model/RecordsLockRequest
 * @version 0.0.1
 */
class RecordsLockRequest {
    /**
     * Constructs a new <code>RecordsLockRequest</code>.
     * @alias module:model/RecordsLockRequest
     */
    constructor() { 
        
        RecordsLockRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RecordsLockRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RecordsLockRequest} obj Optional instance to populate.
     * @return {module:model/RecordsLockRequest} The populated <code>RecordsLockRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecordsLockRequest();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], [RecordLockID]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RecordsLockRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RecordsLockRequest</code>.
     */
    static validateJSON(data) {
        if (data['ids']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ids'])) {
                throw new Error("Expected the field `ids` to be an array in the JSON data but got " + data['ids']);
            }
            // validate the optional field `ids` (array)
            for (const item of data['ids']) {
                RecordLockID.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/RecordLockID>} ids
 */
RecordsLockRequest.prototype['ids'] = undefined;






export default RecordsLockRequest;

