/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ChildRecord from './ChildRecord';

/**
 * The RecordChildrenPage model module.
 * @module model/RecordChildrenPage
 * @version 0.0.1
 */
export default class RecordChildrenPage {
  /**
   * Constructs a new <code>RecordChildrenPage</code>.
   * @alias module:model/RecordChildrenPage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RecordChildrenPage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecordChildrenPage} obj Optional instance to populate.
   * @return {module:model/RecordChildrenPage} The populated <code>RecordChildrenPage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RecordChildrenPage();
      if (data.hasOwnProperty('nextPageToken'))
        obj.nextPageToken = ApiClient.convertToType(data['nextPageToken'], 'String');
      if (data.hasOwnProperty('records'))
        obj.records = ApiClient.convertToType(data['records'], [ChildRecord]);
    }
    return obj;
  }
}

/**
 * Token to retrieve the next page of results, blank if done.
 * @member {String} nextPageToken
 */
RecordChildrenPage.prototype.nextPageToken = undefined;

/**
 * @member {Array.<module:model/ChildRecord>} records
 */
RecordChildrenPage.prototype.records = undefined;

