/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AuditUser from './AuditUser';

/**
 * The RecordRestoredFrom model module.
 * @module model/RecordRestoredFrom
 * @version 0.0.1
 */
export default class RecordRestoredFrom {
  /**
   * Constructs a new <code>RecordRestoredFrom</code>.
   * @alias module:model/RecordRestoredFrom
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RecordRestoredFrom</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecordRestoredFrom} obj Optional instance to populate.
   * @return {module:model/RecordRestoredFrom} The populated <code>RecordRestoredFrom</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RecordRestoredFrom();
      if (data.hasOwnProperty('activityID'))
        obj.activityID = ApiClient.convertToType(data['activityID'], 'String');
      if (data.hasOwnProperty('added'))
        obj.added = ApiClient.convertToType(data['added'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('modified'))
        obj.modified = ApiClient.convertToType(data['modified'], 'Date');
      if (data.hasOwnProperty('user'))
        obj.user = AuditUser.constructFromObject(data['user']);
    }
    return obj;
  }
}

/**
 * Activity ID that restored the record.
 * @member {String} activityID
 */
RecordRestoredFrom.prototype.activityID = undefined;

/**
 * Added time of the new record.
 * @member {Date} added
 */
RecordRestoredFrom.prototype.added = undefined;

/**
 * ID of the original record.
 * @member {String} id
 */
RecordRestoredFrom.prototype.id = undefined;

/**
 * Modified time of the original record.
 * @member {Date} modified
 */
RecordRestoredFrom.prototype.modified = undefined;

/**
 * @member {module:model/AuditUser} user
 */
RecordRestoredFrom.prototype.user = undefined;

