/**
 * GRAX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuditUser from './AuditUser';

/**
 * The RecordPurged model module.
 * @module model/RecordPurged
 * @version 0.0.1
 */
class RecordPurged {
    /**
     * Constructs a new <code>RecordPurged</code>.
     * @alias module:model/RecordPurged
     */
    constructor() { 
        
        RecordPurged.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RecordPurged</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RecordPurged} obj Optional instance to populate.
     * @return {module:model/RecordPurged} The populated <code>RecordPurged</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecordPurged();

            if (data.hasOwnProperty('activityID')) {
                obj['activityID'] = ApiClient.convertToType(data['activityID'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = AuditUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RecordPurged</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RecordPurged</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['activityID'] && !(typeof data['activityID'] === 'string' || data['activityID'] instanceof String)) {
            throw new Error("Expected the field `activityID` to be a primitive type in the JSON string but got " + data['activityID']);
        }
        // validate the optional field `user`
        if (data['user']) { // data not null
          AuditUser.validateJSON(data['user']);
        }

        return true;
    }


}



/**
 * ID of the activity that purged the record.
 * @member {String} activityID
 */
RecordPurged.prototype['activityID'] = undefined;

/**
 * Time the record was purged.
 * @member {Date} time
 */
RecordPurged.prototype['time'] = undefined;

/**
 * @member {module:model/AuditUser} user
 */
RecordPurged.prototype['user'] = undefined;






export default RecordPurged;

