/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AuditUser from './AuditUser';

/**
 * The RecordPurged model module.
 * @module model/RecordPurged
 * @version 0.0.1
 */
export default class RecordPurged {
  /**
   * Constructs a new <code>RecordPurged</code>.
   * @alias module:model/RecordPurged
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RecordPurged</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecordPurged} obj Optional instance to populate.
   * @return {module:model/RecordPurged} The populated <code>RecordPurged</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RecordPurged();
      if (data.hasOwnProperty('activityID'))
        obj.activityID = ApiClient.convertToType(data['activityID'], 'String');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Date');
      if (data.hasOwnProperty('user'))
        obj.user = AuditUser.constructFromObject(data['user']);
    }
    return obj;
  }
}

/**
 * ID of the activity that purged the record.
 * @member {String} activityID
 */
RecordPurged.prototype.activityID = undefined;

/**
 * Time the record was purged.
 * @member {Date} time
 */
RecordPurged.prototype.time = undefined;

/**
 * @member {module:model/AuditUser} user
 */
RecordPurged.prototype.user = undefined;

