/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RecordField model module.
 * @module model/RecordField
 * @version 0.0.1
 */
export default class RecordField {
  /**
   * Constructs a new <code>RecordField</code>.
   * @alias module:model/RecordField
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RecordField</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecordField} obj Optional instance to populate.
   * @return {module:model/RecordField} The populated <code>RecordField</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RecordField();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * Field name.
 * @member {String} name
 */
RecordField.prototype.name = undefined;

/**
 * Field value.
 * @member {String} value
 */
RecordField.prototype.value = undefined;

