/**
 * GRAX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Record from './Record';

/**
 * The RecordVersionsPage model module.
 * @module model/RecordVersionsPage
 * @version 0.0.1
 */
class RecordVersionsPage {
    /**
     * Constructs a new <code>RecordVersionsPage</code>.
     * @alias module:model/RecordVersionsPage
     */
    constructor() { 
        
        RecordVersionsPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RecordVersionsPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RecordVersionsPage} obj Optional instance to populate.
     * @return {module:model/RecordVersionsPage} The populated <code>RecordVersionsPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecordVersionsPage();

            if (data.hasOwnProperty('nextPageToken')) {
                obj['nextPageToken'] = ApiClient.convertToType(data['nextPageToken'], 'String');
            }
            if (data.hasOwnProperty('records')) {
                obj['records'] = ApiClient.convertToType(data['records'], [Record]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RecordVersionsPage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RecordVersionsPage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['nextPageToken'] && !(typeof data['nextPageToken'] === 'string' || data['nextPageToken'] instanceof String)) {
            throw new Error("Expected the field `nextPageToken` to be a primitive type in the JSON string but got " + data['nextPageToken']);
        }
        if (data['records']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['records'])) {
                throw new Error("Expected the field `records` to be an array in the JSON data but got " + data['records']);
            }
            // validate the optional field `records` (array)
            for (const item of data['records']) {
                Record.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Token to retrieve the next page of results, blank if done.
 * @member {String} nextPageToken
 */
RecordVersionsPage.prototype['nextPageToken'] = undefined;

/**
 * Record versions.
 * @member {Array.<module:model/Record>} records
 */
RecordVersionsPage.prototype['records'] = undefined;






export default RecordVersionsPage;

