/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SearchFieldFilter model module.
 * @module model/SearchFieldFilter
 * @version 0.0.1
 */
export default class SearchFieldFilter {
  /**
   * Constructs a new <code>SearchFieldFilter</code>.
   * @alias module:model/SearchFieldFilter
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SearchFieldFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchFieldFilter} obj Optional instance to populate.
   * @return {module:model/SearchFieldFilter} The populated <code>SearchFieldFilter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchFieldFilter();
      if (data.hasOwnProperty('field'))
        obj.field = ApiClient.convertToType(data['field'], 'String');
      if (data.hasOwnProperty('filterType'))
        obj.filterType = ApiClient.convertToType(data['filterType'], 'String');
      if (data.hasOwnProperty('not'))
        obj.not = ApiClient.convertToType(data['not'], 'Boolean');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} field
 */
SearchFieldFilter.prototype.field = undefined;

/**
 * @member {String} filterType
 */
SearchFieldFilter.prototype.filterType = undefined;

/**
 * @member {Boolean} not
 */
SearchFieldFilter.prototype.not = undefined;

/**
 * @member {String} value
 */
SearchFieldFilter.prototype.value = undefined;

