/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SearchRecord from './SearchRecord';

/**
 * The SearchRecordsPage model module.
 * @module model/SearchRecordsPage
 * @version 0.0.1
 */
export default class SearchRecordsPage {
  /**
   * Constructs a new <code>SearchRecordsPage</code>.
   * @alias module:model/SearchRecordsPage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SearchRecordsPage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchRecordsPage} obj Optional instance to populate.
   * @return {module:model/SearchRecordsPage} The populated <code>SearchRecordsPage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchRecordsPage();
      if (data.hasOwnProperty('nextContinuePageToken'))
        obj.nextContinuePageToken = ApiClient.convertToType(data['nextContinuePageToken'], 'String');
      if (data.hasOwnProperty('nextPageToken'))
        obj.nextPageToken = ApiClient.convertToType(data['nextPageToken'], 'String');
      if (data.hasOwnProperty('records'))
        obj.records = ApiClient.convertToType(data['records'], [SearchRecord]);
    }
    return obj;
  }
}

/**
 * Token to retrieve the next page of running search results.
 * @member {String} nextContinuePageToken
 */
SearchRecordsPage.prototype.nextContinuePageToken = undefined;

/**
 * Token to retrieve the next page of results, blank if done.
 * @member {String} nextPageToken
 */
SearchRecordsPage.prototype.nextPageToken = undefined;

/**
 * @member {Array.<module:model/SearchRecord>} records
 */
SearchRecordsPage.prototype.records = undefined;

