/**
 * GRAX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Search from './Search';

/**
 * The SearchesPage model module.
 * @module model/SearchesPage
 * @version 0.0.1
 */
class SearchesPage {
    /**
     * Constructs a new <code>SearchesPage</code>.
     * @alias module:model/SearchesPage
     */
    constructor() { 
        
        SearchesPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchesPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchesPage} obj Optional instance to populate.
     * @return {module:model/SearchesPage} The populated <code>SearchesPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchesPage();

            if (data.hasOwnProperty('nextPageToken')) {
                obj['nextPageToken'] = ApiClient.convertToType(data['nextPageToken'], 'String');
            }
            if (data.hasOwnProperty('searches')) {
                obj['searches'] = ApiClient.convertToType(data['searches'], [Search]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchesPage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchesPage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['nextPageToken'] && !(typeof data['nextPageToken'] === 'string' || data['nextPageToken'] instanceof String)) {
            throw new Error("Expected the field `nextPageToken` to be a primitive type in the JSON string but got " + data['nextPageToken']);
        }
        if (data['searches']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['searches'])) {
                throw new Error("Expected the field `searches` to be an array in the JSON data but got " + data['searches']);
            }
            // validate the optional field `searches` (array)
            for (const item of data['searches']) {
                Search.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Token to retrieve the next page of results, blank if done.
 * @member {String} nextPageToken
 */
SearchesPage.prototype['nextPageToken'] = undefined;

/**
 * @member {Array.<module:model/Search>} searches
 */
SearchesPage.prototype['searches'] = undefined;






export default SearchesPage;

