/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SearchLimits model module.
 * @module model/SearchLimits
 * @version 0.0.1
 */
export default class SearchLimits {
  /**
   * Constructs a new <code>SearchLimits</code>.
   * @alias module:model/SearchLimits
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SearchLimits</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchLimits} obj Optional instance to populate.
   * @return {module:model/SearchLimits} The populated <code>SearchLimits</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchLimits();
      if (data.hasOwnProperty('results'))
        obj.results = ApiClient.convertToType(data['results'], 'Number');
    }
    return obj;
  }
}

/**
 * Stop search after this many results are found.
 * @member {Number} results
 */
SearchLimits.prototype.results = undefined;

