/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SearchFilters from './SearchFilters';
import SearchLimits from './SearchLimits';

/**
 * The SearchCreate model module.
 * @module model/SearchCreate
 * @version 0.0.1
 */
export default class SearchCreate {
  /**
   * Constructs a new <code>SearchCreate</code>.
   * @alias module:model/SearchCreate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SearchCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchCreate} obj Optional instance to populate.
   * @return {module:model/SearchCreate} The populated <code>SearchCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchCreate();
      if (data.hasOwnProperty('filters'))
        obj.filters = SearchFilters.constructFromObject(data['filters']);
      if (data.hasOwnProperty('limits'))
        obj.limits = SearchLimits.constructFromObject(data['limits']);
      if (data.hasOwnProperty('notify'))
        obj.notify = ApiClient.convertToType(data['notify'], 'Boolean');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('reverse'))
        obj.reverse = ApiClient.convertToType(data['reverse'], 'Boolean');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('timeField'))
        obj.timeField = ApiClient.convertToType(data['timeField'], 'String');
      if (data.hasOwnProperty('timeFieldMax'))
        obj.timeFieldMax = ApiClient.convertToType(data['timeFieldMax'], 'Date');
      if (data.hasOwnProperty('timeFieldMin'))
        obj.timeFieldMin = ApiClient.convertToType(data['timeFieldMin'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {module:model/SearchFilters} filters
 */
SearchCreate.prototype.filters = undefined;

/**
 * @member {module:model/SearchLimits} limits
 */
SearchCreate.prototype.limits = undefined;

/**
 * Whether to notify when the search is complete.
 * @member {Boolean} notify
 */
SearchCreate.prototype.notify = undefined;

/**
 * Object to search.
 * @member {String} _object
 */
SearchCreate.prototype._object = undefined;

/**
 * Whether to search in reverse order.
 * @member {Boolean} reverse
 */
SearchCreate.prototype.reverse = undefined;

/**
 * Status of the records to search.
 * @member {String} status
 */
SearchCreate.prototype.status = undefined;

/**
 * Time field to search. Can be 'createdAt', 'modifiedAt', 'latestModifiedAt', 'rangeLatestModifiedAt', 'allModifiedAt', 'deletedAt' or 'purgedAt'. Defaults to 'createdAt'.
 * @member {String} timeField
 */
SearchCreate.prototype.timeField = undefined;

/**
 * Maximum time for the search.
 * @member {Date} timeFieldMax
 */
SearchCreate.prototype.timeFieldMax = undefined;

/**
 * Minimum time for the search.
 * @member {Date} timeFieldMin
 */
SearchCreate.prototype.timeFieldMin = undefined;

