/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Search from './Search';

/**
 * The SearchesPage model module.
 * @module model/SearchesPage
 * @version 0.0.1
 */
export default class SearchesPage {
  /**
   * Constructs a new <code>SearchesPage</code>.
   * @alias module:model/SearchesPage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SearchesPage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchesPage} obj Optional instance to populate.
   * @return {module:model/SearchesPage} The populated <code>SearchesPage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchesPage();
      if (data.hasOwnProperty('nextPageToken'))
        obj.nextPageToken = ApiClient.convertToType(data['nextPageToken'], 'String');
      if (data.hasOwnProperty('searches'))
        obj.searches = ApiClient.convertToType(data['searches'], [Search]);
    }
    return obj;
  }
}

/**
 * Token to retrieve the next page of results, blank if done.
 * @member {String} nextPageToken
 */
SearchesPage.prototype.nextPageToken = undefined;

/**
 * @member {Array.<module:model/Search>} searches
 */
SearchesPage.prototype.searches = undefined;

