/*
 * GRAX API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import RecordDeleted from './RecordDeleted';
import RecordField from './RecordField';
import RecordPurged from './RecordPurged';
import RecordRestoredFrom from './RecordRestoredFrom';

/**
 * The SearchRecord model module.
 * @module model/SearchRecord
 * @version 0.0.1
 */
export default class SearchRecord {
  /**
   * Constructs a new <code>SearchRecord</code>.
   * @alias module:model/SearchRecord
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SearchRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchRecord} obj Optional instance to populate.
   * @return {module:model/SearchRecord} The populated <code>SearchRecord</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchRecord();
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('deleted'))
        obj.deleted = RecordDeleted.constructFromObject(data['deleted']);
      if (data.hasOwnProperty('fields'))
        obj.fields = ApiClient.convertToType(data['fields'], [RecordField]);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('modified'))
        obj.modified = ApiClient.convertToType(data['modified'], 'Date');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('purged'))
        obj.purged = RecordPurged.constructFromObject(data['purged']);
      if (data.hasOwnProperty('restoredFrom'))
        obj.restoredFrom = RecordRestoredFrom.constructFromObject(data['restoredFrom']);
      if (data.hasOwnProperty('salesforceURL'))
        obj.salesforceURL = ApiClient.convertToType(data['salesforceURL'], 'String');
    }
    return obj;
  }
}

/**
 * Time the record was created.
 * @member {Date} created
 */
SearchRecord.prototype.created = undefined;

/**
 * @member {module:model/RecordDeleted} deleted
 */
SearchRecord.prototype.deleted = undefined;

/**
 * Record fields.
 * @member {Array.<module:model/RecordField>} fields
 */
SearchRecord.prototype.fields = undefined;

/**
 * Record ID.
 * @member {String} id
 */
SearchRecord.prototype.id = undefined;

/**
 * Time the record was modified.
 * @member {Date} modified
 */
SearchRecord.prototype.modified = undefined;

/**
 * Record name.
 * @member {String} name
 */
SearchRecord.prototype.name = undefined;

/**
 * @member {module:model/RecordPurged} purged
 */
SearchRecord.prototype.purged = undefined;

/**
 * @member {module:model/RecordRestoredFrom} restoredFrom
 */
SearchRecord.prototype.restoredFrom = undefined;

/**
 * Salesforce URL for the record.
 * @member {String} salesforceURL
 */
SearchRecord.prototype.salesforceURL = undefined;

