/**
 * GRAX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import ObjectsPage from '../model/ObjectsPage';

/**
* Objects service.
* @module api/ObjectsApi
* @version 0.0.1
*/
export default class ObjectsApi {

    /**
    * Constructs a new ObjectsApi. 
    * @alias module:api/ObjectsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the objectsList operation.
     * @callback module:api/ObjectsApi~objectsListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ObjectsPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List objects
     * @param {Object} opts Optional parameters
     * @param {Number} [maxItems] Maximum number of items to return per page. Fewer or zero may be returned.
     * @param {String} [pageToken] Token returned by previous call to retrieve the subsequent page.
     * @param {module:api/ObjectsApi~objectsListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ObjectsPage}
     */
    objectsList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'maxItems': opts['maxItems'],
        'pageToken': opts['pageToken']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ObjectsPage;
      return this.apiClient.callApi(
        '/api/v2/objects', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
