/**
 * GRAX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import Search from '../model/Search';
import SearchCreate from '../model/SearchCreate';
import SearchRecordsPage from '../model/SearchRecordsPage';
import SearchesPage from '../model/SearchesPage';

/**
* Search service.
* @module api/SearchApi
* @version 0.0.1
*/
export default class SearchApi {

    /**
    * Constructs a new SearchApi. 
    * @alias module:api/SearchApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the searchAbort operation.
     * @callback module:api/SearchApi~searchAbortCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Abort search
     * @param {String} id ID of the search job.
     * @param {module:api/SearchApi~searchAbortCallback} callback The callback function, accepting three arguments: error, data, response
     */
    searchAbort(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling searchAbort");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v2/searches/{id}/abort', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchCreate operation.
     * @callback module:api/SearchApi~searchCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Search} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create search
     * @param {Object} opts Optional parameters
     * @param {module:model/SearchCreate} [searchCreate] 
     * @param {module:api/SearchApi~searchCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Search}
     */
    searchCreate(opts, callback) {
      opts = opts || {};
      let postBody = opts['searchCreate'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Search;
      return this.apiClient.callApi(
        '/api/v2/searches', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchDelete operation.
     * @callback module:api/SearchApi~searchDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete search
     * @param {String} id 
     * @param {module:api/SearchApi~searchDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    searchDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling searchDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v2/searches/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchDownload operation.
     * @callback module:api/SearchApi~searchDownloadCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Download search results
     * @param {String} id ID of the search job.
     * @param {Object} opts Optional parameters
     * @param {String} [fields] Fields to include in the response. If not specified, all fields are included.
     * @param {Boolean} [latest] Whether to download the latest version of each record.
     * @param {module:api/SearchApi~searchDownloadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    searchDownload(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling searchDownload");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'fields': opts['fields'],
        'latest': opts['latest']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/zip'];
      let returnType = 'Blob';
      return this.apiClient.callApi(
        '/api/v2/searches/{id}/download', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchGet operation.
     * @callback module:api/SearchApi~searchGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Search} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get search
     * @param {String} id 
     * @param {module:api/SearchApi~searchGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Search}
     */
    searchGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling searchGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Search;
      return this.apiClient.callApi(
        '/api/v2/searches/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchRecords operation.
     * @callback module:api/SearchApi~searchRecordsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SearchRecordsPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Read search result records
     * @param {String} id ID of the search job.
     * @param {Object} opts Optional parameters
     * @param {String} [fields] Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
     * @param {Boolean} [reverse] Search records in reverse order.
     * @param {Date} [minTime] Minimum record time to include in the response.
     * @param {Number} [maxItems] Maximum number of items to return per page. Fewer or zero may be returned.
     * @param {String} [pageToken] Token returned by previous call to retrieve the subsequent page.
     * @param {module:api/SearchApi~searchRecordsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SearchRecordsPage}
     */
    searchRecords(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling searchRecords");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'fields': opts['fields'],
        'reverse': opts['reverse'],
        'minTime': opts['minTime'],
        'maxItems': opts['maxItems'],
        'pageToken': opts['pageToken']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SearchRecordsPage;
      return this.apiClient.callApi(
        '/api/v2/searches/{id}/records', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchesList operation.
     * @callback module:api/SearchApi~searchesListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SearchesPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List searches
     * @param {Object} opts Optional parameters
     * @param {Number} [maxItems] Maximum number of items to return per page. Fewer or zero may be returned.
     * @param {String} [pageToken] Token returned by previous call to retrieve the subsequent page.
     * @param {module:api/SearchApi~searchesListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SearchesPage}
     */
    searchesList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'maxItems': opts['maxItems'],
        'pageToken': opts['pageToken']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SearchesPage;
      return this.apiClient.callApi(
        '/api/v2/searches', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
