/**
 * GRAX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GraxApi);
  }
}(this, function(expect, GraxApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GraxApi.Deletion();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Deletion', function() {
    it('should create an instance of Deletion', function() {
      // uncomment below and update the code to test Deletion
      //var instance = new GraxApi.Deletion();
      //expect(instance).to.be.a(GraxApi.Deletion);
    });

    it('should have the property caller (base name: "caller")', function() {
      // uncomment below and update the code to test the property caller
      //var instance = new GraxApi.Deletion();
      //expect(instance).to.be();
    });

    it('should have the property cascade (base name: "cascade")', function() {
      // uncomment below and update the code to test the property cascade
      //var instance = new GraxApi.Deletion();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new GraxApi.Deletion();
      //expect(instance).to.be();
    });

    it('should have the property forceCascadeObjects (base name: "forceCascadeObjects")', function() {
      // uncomment below and update the code to test the property forceCascadeObjects
      //var instance = new GraxApi.Deletion();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new GraxApi.Deletion();
      //expect(instance).to.be();
    });

    it('should have the property object (base name: "object")', function() {
      // uncomment below and update the code to test the property object
      //var instance = new GraxApi.Deletion();
      //expect(instance).to.be();
    });

    it('should have the property skipDeletedCheck (base name: "skipDeletedCheck")', function() {
      // uncomment below and update the code to test the property skipDeletedCheck
      //var instance = new GraxApi.Deletion();
      //expect(instance).to.be();
    });

  });

}));
