/**
 * GRAX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GraxApi);
  }
}(this, function(expect, GraxApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GraxApi.SearchCreate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SearchCreate', function() {
    it('should create an instance of SearchCreate', function() {
      // uncomment below and update the code to test SearchCreate
      //var instance = new GraxApi.SearchCreate();
      //expect(instance).to.be.a(GraxApi.SearchCreate);
    });

    it('should have the property filters (base name: "filters")', function() {
      // uncomment below and update the code to test the property filters
      //var instance = new GraxApi.SearchCreate();
      //expect(instance).to.be();
    });

    it('should have the property limits (base name: "limits")', function() {
      // uncomment below and update the code to test the property limits
      //var instance = new GraxApi.SearchCreate();
      //expect(instance).to.be();
    });

    it('should have the property notify (base name: "notify")', function() {
      // uncomment below and update the code to test the property notify
      //var instance = new GraxApi.SearchCreate();
      //expect(instance).to.be();
    });

    it('should have the property object (base name: "object")', function() {
      // uncomment below and update the code to test the property object
      //var instance = new GraxApi.SearchCreate();
      //expect(instance).to.be();
    });

    it('should have the property reverse (base name: "reverse")', function() {
      // uncomment below and update the code to test the property reverse
      //var instance = new GraxApi.SearchCreate();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new GraxApi.SearchCreate();
      //expect(instance).to.be();
    });

    it('should have the property timeField (base name: "timeField")', function() {
      // uncomment below and update the code to test the property timeField
      //var instance = new GraxApi.SearchCreate();
      //expect(instance).to.be();
    });

    it('should have the property timeFieldMax (base name: "timeFieldMax")', function() {
      // uncomment below and update the code to test the property timeFieldMax
      //var instance = new GraxApi.SearchCreate();
      //expect(instance).to.be();
    });

    it('should have the property timeFieldMin (base name: "timeFieldMin")', function() {
      // uncomment below and update the code to test the property timeFieldMin
      //var instance = new GraxApi.SearchCreate();
      //expect(instance).to.be();
    });

  });

}));
