/**
 * GRAX API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GraxApi);
  }
}(this, function(expect, GraxApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GraxApi.Search();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Search', function() {
    it('should create an instance of Search', function() {
      // uncomment below and update the code to test Search
      //var instance = new GraxApi.Search();
      //expect(instance).to.be.a(GraxApi.Search);
    });

    it('should have the property created (base name: "created")', function() {
      // uncomment below and update the code to test the property created
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property deleting (base name: "deleting")', function() {
      // uncomment below and update the code to test the property deleting
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property filterStatus (base name: "filterStatus")', function() {
      // uncomment below and update the code to test the property filterStatus
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property filters (base name: "filters")', function() {
      // uncomment below and update the code to test the property filters
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property limits (base name: "limits")', function() {
      // uncomment below and update the code to test the property limits
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property object (base name: "object")', function() {
      // uncomment below and update the code to test the property object
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property progress (base name: "progress")', function() {
      // uncomment below and update the code to test the property progress
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property recordsFound (base name: "recordsFound")', function() {
      // uncomment below and update the code to test the property recordsFound
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property recordsScanned (base name: "recordsScanned")', function() {
      // uncomment below and update the code to test the property recordsScanned
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property recordsTimeFirst (base name: "recordsTimeFirst")', function() {
      // uncomment below and update the code to test the property recordsTimeFirst
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property recordsTimeLast (base name: "recordsTimeLast")', function() {
      // uncomment below and update the code to test the property recordsTimeLast
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property reverse (base name: "reverse")', function() {
      // uncomment below and update the code to test the property reverse
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property timeField (base name: "timeField")', function() {
      // uncomment below and update the code to test the property timeField
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property timeFieldMax (base name: "timeFieldMax")', function() {
      // uncomment below and update the code to test the property timeFieldMax
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property timeFieldMin (base name: "timeFieldMin")', function() {
      // uncomment below and update the code to test the property timeFieldMin
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

    it('should have the property updated (base name: "updated")', function() {
      // uncomment below and update the code to test the property updated
      //var instance = new GraxApi.Search();
      //expect(instance).to.be();
    });

  });

}));
